#!/usr/bin/env python3
"""Renders the bitmap fonts used by the OLED (components/ssd1306/src/fonts.c) from DejaVu TTFs.

small: 5x8 cells, ASCII 32..126, DejaVu Sans Mono 8 px (column bytes, LSB = top row)
big:   digits 0-9, '-', ' ', 24 px high, DejaVu Sans Bold (3 page bytes per column)
Requires Pillow: pip install pillow
"""
import sys
from PIL import Image, ImageDraw, ImageFont

MONO = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"


def render(font, ch, w, h, dy):
    im = Image.new("1", (w, h), 0)
    d = ImageDraw.Draw(im)
    d.fontmode = "1"
    d.text((0, dy), ch, fill=1, font=font)
    return im


def columns(im, w, h):
    pages = (h + 7) // 8
    out = []
    for x in range(w):
        for p in range(pages):
            b = 0
            for bit in range(8):
                y = p * 8 + bit
                if y < h and im.getpixel((x, y)):
                    b |= 1 << bit
            out.append(b)
    return out


def main(path):
    small = ImageFont.truetype(MONO, 8)
    big = ImageFont.truetype(BOLD, 24)
    lines = ["// GENERATED by tools/gen_fonts.py — do not edit.", '#include "ssd1306.h"', ""]
    lines.append("const uint8_t ssd1306_font5x8[95][5] = {")
    for c in range(32, 127):
        cols = columns(render(small, chr(c), 5, 8, -1), 5, 8)
        lines.append("    {" + ", ".join(f"0x{b:02x}" for b in cols) + f"}},  // {chr(c)!r}")
    lines.append("};")
    lines.append("")
    glyphs = "0123456789- "
    widths = []
    data = []
    for ch in glyphs:
        w = max(1, int(big.getlength(ch))) if ch != " " else 6
        im = render(big, ch, w, 24, -4)
        widths.append(w)
        data.append(columns(im, w, 24))
    lines.append(f"const char ssd1306_big_glyphs[] = \"{glyphs}\";")
    lines.append("const uint8_t ssd1306_big_width[] = {" + ", ".join(map(str, widths)) + "};")
    for i, d in enumerate(data):
        lines.append(f"static const uint8_t big_{i}[] = {{" + ", ".join(f"0x{b:02x}" for b in d) + "};")
    lines.append("const uint8_t *const ssd1306_big_data[] = {" + ", ".join(f"big_{i}" for i in range(len(data))) + "};")
    open(path, "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "components/ssd1306/src/fonts.c")
