// Minimal SSD1306 driver with a frame buffer, for the 0.42" 72x40 OLED (and other sizes).
#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "driver/i2c_master.h"
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint8_t width;      // visible columns (72)
    uint8_t height;     // visible rows (40)
    uint8_t x_offset;   // first visible column in controller RAM (28 for 72x40)
    uint8_t address;    // I2C address (0x3C)
} ssd1306_config_t;

#define SSD1306_72X40 {.width = 72, .height = 40, .x_offset = 28, .address = 0x3C}

typedef struct ssd1306 *ssd1306_handle_t;

esp_err_t ssd1306_init(i2c_master_bus_handle_t bus, const ssd1306_config_t *cfg, ssd1306_handle_t *out);
void ssd1306_clear(ssd1306_handle_t d);
void ssd1306_pixel(ssd1306_handle_t d, int x, int y, bool on);
void ssd1306_fill_rect(ssd1306_handle_t d, int x, int y, int w, int h, bool on);
void ssd1306_hline(ssd1306_handle_t d, int x, int y, int w);
// Small 5x8 font (ASCII). Returns the x after the text.
int ssd1306_text(ssd1306_handle_t d, int x, int y, const char *s);
int ssd1306_text_width(const char *s);
// Big digits (0-9, '-', ' '), 24 px high. Returns the x after the text.
int ssd1306_big(ssd1306_handle_t d, int x, int y, const char *s);
int ssd1306_big_width_of(const char *s);
void ssd1306_invert_rect(ssd1306_handle_t d, int x, int y, int w, int h);
esp_err_t ssd1306_flush(ssd1306_handle_t d);
esp_err_t ssd1306_contrast(ssd1306_handle_t d, uint8_t level);
esp_err_t ssd1306_power(ssd1306_handle_t d, bool on);
uint8_t ssd1306_width(ssd1306_handle_t d);
uint8_t ssd1306_height(ssd1306_handle_t d);

// Fonts (fonts.c, generated by tools/gen_fonts.py)
extern const uint8_t ssd1306_font5x8[95][5];
extern const char ssd1306_big_glyphs[];
extern const uint8_t ssd1306_big_width[];
extern const uint8_t *const ssd1306_big_data[];

#ifdef __cplusplus
}
#endif
